import os
from dotenv import load_dotenv

load_dotenv()

DISCORD_WEBHOOK_URL = os.getenv("VOLUME_TRADING_HOOK") or "https://discord.com/api/webhooks/1491364569069781134/N-809nn5JnH1mxxcfopl9NK7u2S3kQLKr-c1QPBSkBqkI2uaDldbK8Om5cf7t4Q3r_8R"

GOOGLE_API_KEY = os.getenv("GEMINI_KEY", "")

VOLUME_SPIKE_THRESHOLD = 2.0

SIGNAL_COOLDOWN_SECONDS = 60

SUMMARY_INTERVAL_SECONDS = 3600

ROLLING_WINDOW_SECONDS = 600

TRADE_AGGREGATION_SECONDS = 10

VOLUME_SPIKE_CHECK_INTERVAL = 30

ORDER_BOOK_CHECK_INTERVAL = 60

MIN_TRADE_SIZE_BTC = 0.001

SIGNIFICANT_TRADE_SIZE_BTC = 0.01

LARGE_TRADE_USD_THRESHOLD = 25000

DISCORD_TRADE_THRESHOLD = 750000

BTC_USD_PRICE = None

PATTERN_UPDATE_INTERVAL = 3600

PRICE_OUTCOME_INTERVALS = [60, 180, 300]

EXCHANGES_TO_MONITOR = [
    "binance",
    "coinbase",
    "okx",
    "hyperliquid",
    "hyperliquid_spot",
    "binance_perp",
]

BTC_PAIRS = [
    "BTC/USDT",
    "BTC-USD",
]

TRADE_KEEP_HOURS = 2

TRADE_CLEANUP_INTERVAL_HOURS = 1
